"""empty message

Revision ID: 6bd2d88173ce
Revises: 235d25625605
Create Date: 2024-08-27 09:46:56.580996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bd2d88173ce'
down_revision = '235d25625605'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('uid')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('population',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('rotation_period',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('orbital_period',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('gravity',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('terrain',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('surface_water',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_column('uid')

    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.drop_column('uid')

    with op.batch_alter_table('starship', schema=None) as batch_op:
        batch_op.drop_column('uid')

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_column('uid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('starship', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.INTEGER(), autoincrement=False, nullable=False))

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('surface_water',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('terrain',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('gravity',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('orbital_period',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('rotation_period',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('population',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
