"""empty message

Revision ID: e7e4185980ad
Revises: 6bd2d88173ce
Create Date: 2024-08-27 20:33:21.330652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7e4185980ad'
down_revision = '6bd2d88173ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles_favorites')
    op.drop_table('starships_favorites')
    op.drop_table('characters_favorites')
    op.drop_table('planets_favorites')
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('planet_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('starship_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vehicle_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('character_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'starship', ['starship_id'], ['id'])
        batch_op.create_foreign_key(None, 'characters', ['character_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'planet', ['planet_id'], ['id'])
        batch_op.create_foreign_key(None, 'vehicle', ['vehicle_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('character_id')
        batch_op.drop_column('vehicle_id')
        batch_op.drop_column('starship_id')
        batch_op.drop_column('planet_id')
        batch_op.drop_column('user_id')

    op.create_table('planets_favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('planet_favorite', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['planet_favorite'], ['planet.id'], name='planets_favorites_planet_favorite_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='planets_favorites_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='planets_favorites_pkey')
    )
    op.create_table('characters_favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('character_favorite', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['character_favorite'], ['characters.id'], name='characters_favorites_character_favorite_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='characters_favorites_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='characters_favorites_pkey')
    )
    op.create_table('starships_favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('starship_favorite', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['starship_favorite'], ['starship.id'], name='starships_favorites_starship_favorite_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='starships_favorites_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='starships_favorites_pkey')
    )
    op.create_table('vehicles_favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vehicle_favorite', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='vehicles_favorites_user_id_fkey'),
    sa.ForeignKeyConstraint(['vehicle_favorite'], ['vehicle.id'], name='vehicles_favorites_vehicle_favorite_fkey'),
    sa.PrimaryKeyConstraint('id', name='vehicles_favorites_pkey')
    )
    # ### end Alembic commands ###
